# Project: 
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 
LINKOBJ  = 
LIBS     = -L"D:/Embercadero/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = config.mak.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Embercadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)
